[package]
name = "ceetle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctl_proc_macro = { path = "ctl_proc_macro" }